added local test

diff --git a/devops-infra/jenkins/Jenkinsfile.local b/devops-infra/jenkins/Jenkinsfile.local
--- a/devops-infra/jenkins/Jenkinsfile.local
+++ b/devops-infra/jenkins/Jenkinsfile.local
@@ -16,8 +16,19 @@ pipeline {
             steps {
                 script {
                     sh 'cp $KUBECONFIG ${WORKSPACE}/kubeconfig_fixed'
-                    sh "sed -i 's|server: https://.*|server: https://host.docker.internal:6443|g' ${WORKSPACE}/kubeconfig_fixed"
                     sh 'chmod 600 ${WORKSPACE}/kubeconfig_fixed'
+                    sh '''
+                        export KUBECONFIG=${WORKSPACE}/kubeconfig_fixed
+                        CLUSTER_NAME=$(kubectl config view --minify -o jsonpath='{.clusters[0].name}')
+                        if [ -z "$CLUSTER_NAME" ]; then
+                            echo "Error: Could not find cluster name in kubeconfig"
+                            exit 1
+                        fi
+                        kubectl config set-cluster $CLUSTER_NAME --server=https://host.docker.internal:6443
+                        kubectl config set-cluster $CLUSTER_NAME --insecure-skip-tls-verify=true
+                        echo "Updated server configuration:"
+                        kubectl config view --minify | grep server
+                    '''
                 }
                 withEnv(["KUBECONFIG=${env.WORKSPACE}/kubeconfig_fixed"]) {
                     sh 'terraform -version'
